import type { Metadata } from "next";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function dashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="h-[80px] inset-y-0 w-full fixed z-50">
        <Navbar />
      </div>
      <main>{children}</main>
    </div>
  );
}
